### PR TITLE
tests: mender-test-containers

### PR DESCRIPTION
**Pull request by mchalski**
https://tracker.mender.io/browse/QA-260

_I don't understand coveralls failures - but the PR is ready otherwise... the only reason I can find is extra lines that artificially decrease the coverage_

### CODE REVIEW

**Review by lluiscampos — CHANGES_REQUESTED** [review]
The test changes look good to me.

The `tests/Dockerfile` is now obsolete, we should replace the content. See https://github.com/mendersoftware/deviceauth/commit/65d4f9b453ca920ebbe229672f1bcaa8a7de4cf6

**Comment by lluiscampos** [comment]
> _I don't understand coveralls failures - but the PR is ready otherwise... the only reason I can find is extra lines that artificially decrease the coverage_

There seems to be 7 missing tests. The log says `30 passed, 7 deselected` while for `master` we have `37 passed, 7 deselected`.

I am looking a bit more into it

**Comment by mchalski** [comment]
@lluiscampos I got it - another silent warning:
``` 
tests/test_artifact.py:36                                                                                                            
acceptance_1                     |   /testing/tests/test_artifact.py:36: PytestCollectionWarning: cannot collect test class 'TestArtifact' because it has a __init__ con
structor (from: tests/test_artifact.py)                                                                                                                                 
acceptance_1                     |     class TestArtifact(ArtifactsClient):
```

`TestArtifact` is the 7 missing tests, will fix.

**Comment by lluiscampos** [comment]
> @lluiscampos I got it - another silent warning:
> 
> ```
> tests/test_artifact.py:36                                                                                                            
> acceptance_1                     |   /testing/tests/test_artifact.py:36: PytestCollectionWarning: cannot collect test class 'TestArtifact' because it has a __init__ con
> structor (from: tests/test_artifact.py)                                                                                                                                 
> acceptance_1                     |     class TestArtifact(ArtifactsClient):
> ```
> 
> `TestArtifact` is the 7 missing tests, will fix.

It took me more time, but I found it too! Good.

**Review by lluiscampos — APPROVED** [review]

**Comment by mchalski** [comment]
@lluiscampos can you force a merge? it's stuck on `mender-qa` but I didn't start any pipeline

**Pull request merged**
