### PR TITLE
feat: expose the image object in the device deployment API endpoints

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: Title
Ticket: MEN-6138

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

Sample response (one configuration deployment, one software deployment):

```
[
    {
        "id": "3b3e82ab-8c00-4fc7-b6f2-9fc8d92d8c69",
        "deployment": {
            "name": "configuration-641b8593-50ff-4153-ba9c-088a9fe064cf",
            "artifact_name": "configuration-641b8593-50ff-4153-ba9c-088a9fe064cf",
            "created": "2022-12-21T15:06:44.347Z",
            "finished": "2022-12-21T15:20:51.179Z",
            "id": "641b8593-50ff-4153-ba9c-088a9fe064cf",
            "status": "finished",
            "device_count": 1,
            "max_devices": 1,
            "configuration": "eyJhIjoiYiIsImMiOiJkIn0=",
            "type": "configuration"
        },
        "device": {
            "created": "2022-12-21T15:06:44.347Z",
            "finished": "2022-12-21T15:20:51.177Z",
            "status": "success",
            "id": "bdc8a64d-ab4b-46af-93f1-6f763208ab37",
            "log": false
        }
    },
    {
        "id": "5fe9307e-91b7-44ca-a2f9-55eb9fbc5983",
        "deployment": {
            "name": "All devices",
            "artifact_name": "161943119.pdf",
            "created": "2022-12-21T15:04:40.446Z",
            "finished": "2022-12-21T15:06:13.908Z",
            "id": "e307d74d-9b8d-46e2-81fa-8b31fff41f04",
            "artifacts": [
                "4a6b9b28-83ac-4b49-97c8-35781e11d832"
            ],
            "status": "finished",
            "device_count": 1,
            "max_devices": 1,
            "type": "software"
        },
        "device": {
            "created": "2022-12-21T15:04:40.446Z",
            "finished": "2022-12-21T15:06:13.905Z",
            "status": "success",
            "id": "bdc8a64d-ab4b-46af-93f1-6f763208ab37",
            "image": {
                "id": "4a6b9b28-83ac-4b49-97c8-35781e11d832",
                "name": "161943119.pdf",
                "device_types_compatible": [
                    "test"
                ],
                "info": {
                    "format": "mender",
                    "version": 3
                },
                "signed": false,
                "updates": [
                    {
                        "type_info": {
                            "type": "single-file"
                        },
                        "files": [
                            {
                                "name": "dest_dir",
                                "checksum": "65ec307145867b81f8c464835723ef5843ecd12e46515e9b4efedee628e3d868",
                                "size": 26,
                                "date": "2022-12-21T15:04:34Z"
                            },
                            {
                                "name": "filename",
                                "checksum": "78f4bc931f187f5c00bc88dfe5a0c9edf0e7628e05b1fce953edf2b64d93f94f",
                                "size": 14,
                                "date": "2022-12-21T15:04:34Z"
                            },
                            {
                                "name": "permissions",
                                "checksum": "0a2a5ea75282bf45dfcd2df50bea57b953ffecba63d8809c4e9abd233b828f73",
                                "size": 4,
                                "date": "2022-12-21T15:04:34Z"
                            },
                            {
                                "name": "161943119.pdf",
                                "checksum": "d7f28dc34aa5dae4b3ad6106973df136483d56d304c22964ef3f2b26aa6cfd57",
                                "size": 158554,
                                "date": "2022-12-21T15:04:34Z"
                            }
                        ],
                        "meta_data": []
                    }
                ],
                "artifact_provides": {
                    "artifact_name": "161943119.pdf",
                    "rootfs-image.single-file.version": "161943119.pdf"
                },
                "artifact_depends": {
                    "device_type": [
                        "test"
                    ]
                },
                "clears_artifact_provides": [
                    "rootfs-image.single-file.*"
                ],
                "size": 158208,
                "modified": "2022-12-21T15:04:34.295Z"
            },
            "log": false
        }
    },
    {
        "id": "b4018806-20ea-443d-a518-c714d7393d62",
        "deployment": {
            "name": "All devices",
            "artifact_name": "mender-demo-artifact-3.4.0",
            "created": "2022-12-21T15:03:16.128Z",
            "finished": "2022-12-21T15:03:20.427Z",
            "id": "0035721e-0805-46b8-954f-bb5b96d51db6",
            "artifacts": [
                "9f34c898-dd95-479c-8a04-696db166f930"
            ],
            "status": "finished",
            "device_count": 1,
            "max_devices": 1,
            "type": "software"
        },
        "device": {
            "created": "2022-12-21T15:03:16.128Z",
            "finished": "2022-12-21T15:03:20.425Z",
            "status": "noartifact",
            "id": "bdc8a64d-ab4b-46af-93f1-6f763208ab37",
            "log": false
        }
    }
]
```

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --fast

**Comment by kjaskiewiczz** [comment]
there are other endpoints which returns device object e.g. `/deployments/{deployment_id}/devices/list`
if I'm not wrong, with this change, `image` will also be included there, which I'm not sure is the desired behavior

**Comment by tranchitella** [comment]
> there are other endpoints which returns device object e.g. `/deployments/{deployment_id}/devices/list` if I'm not wrong, with this change, `image` will also be included there, which I'm not sure is the desired behavior

I thought the idea behind the task was including the images everywhere. Am I wrong?

**Comment by kjaskiewiczz** [comment]
> I thought the idea behind the task was including the images everywhere. Am I wrong?

my original idea was to add it only to device deployment objects returned by deployments history endpoint only, because there we are getting detailed information about single device (I know there can be many device deployments);
in case of endpoints returning list of devices, my understanding was that we don't need this information and this is why the filed was decorated with `json "-"`; we probably need even less information there, but that's a different story;
I can't see an issue with extending device deployment objects everywhere, but my personal approach would be to change as little as possible, which, in this case, means keeping other endpoints unchanged

**Comment by tranchitella** [comment]
> > I thought the idea behind the task was including the images everywhere. Am I wrong?
> 
> my original idea was to add it only to device deployment objects returned by deployments history endpoint only, because there we are getting detailed information about single device (I know there can be many device deployments); in case of endpoints returning list of devices, my understanding was that we don't need this information and this is why the filed was decorated with `json "-"`; we probably need even less information there, but that's a different story; I can't see an issue with extending device deployment objects everywhere, but my personal approach would be to change as little as possible, which, in this case, means keeping other endpoints unchanged

ok, noted; let me rework it, then.

**Comment by tranchitella** [comment]
@kjaskiewiczz something like this?

**Comment by kjaskiewiczz** [comment]
@tranchitella yes, thank you; it's not compiling, but I'm approving in advance ;)

**Review by kjaskiewiczz — APPROVED** [review]

**Comment by tranchitella** [comment]
> @tranchitella yes, thank you; it's not compiling, but I'm approving in advance ;)

you know, when you have all tests green, then you refactor a little detail just before pushing.
Sorry, it should be okay now.

**Comment by kjaskiewiczz** [comment]
> you know, when you have all tests green, then you refactor a little detail just before pushing.

exactly! it's happening to me almost every time I'm doing such a thing

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --fast

**Pull request merged**
