### PR TITLE
feat: Skip verification and download of the artifact via DEPLYOMENTS_…

### PR DESCRIPTION
**Pull request by merlin-northern**
…DIRECT_UPLOAD_SKIP_VERIFY

Changelog: Title
Ticket: MEN-6474

### CODE REVIEW

**Comment by merlin-northern** [comment]
@kjaskiewiczz there is 0 tests, but I need an early review on this. I tested manually with minio -- works. I will try to test with S3.

**Review by kjaskiewiczz — APPROVED** [review]
except for some comments here and there it looks good, but I didn't tested if it actually works

**Comment by merlin-northern** [comment]
> except for some comments here and there it looks good, but I didn't tested if it actually works

sorry about then -- I noticed after I had requested review, I will clean them.

**Comment by merlin-northern** [comment]
the changes after review [are cosmetic](https://github.com/mendersoftware/deployments/compare/4cd1f02dc3b85f9fe68987ef4335cbbd5fdf6674..8afaf9f791ba5270d8dd3a9b01886a092350da73). I added two unit tests scenario and moved acceptance tests to skip verify, the tests cannot be parametrized and when we added direct upload we just added it to the docker compose file.

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please

**Pull request merged**
