### PR TITLE
feat: sort releases by artifacts_count and tags

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: Title
Ticket: MEN-6353

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please

**Review by tranchitella — APPROVED** [review]
It looks good; however, what will happen when we apply the migration to an existing database? All the releases will be "artifacts_count" = 0, right?

**Comment by merlin-northern** [comment]
> It looks good; however, what will happen when we apply the migration to an existing database? All the releases will be "artifacts_count" = 0, right?

right! now we set the counts in migration: commit: [0feb7143ba11570e921dd810e2f0806b34a25461](https://github.com/mendersoftware/deployments/pull/908/commits/0feb7143ba11570e921dd810e2f0806b34a25461) I had to bump the minVersion as well, since with artifacts_count=0 the sort will not work as expected.

**Review by tranchitella — APPROVED** [review]

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please

**Comment by merlin-northern** [comment]
last push was just a squash.

**Pull request merged**
