### PR TITLE
MEN-3026 HEALTHCHECK added

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
> I suggest closing this PR. While I support the addition of health checks, I believe this should be implemented in a common way exposing a `/healthz` end-point.

so you do not like that [/health](https://github.com/mendersoftware/deployments/pull/377/commits/acc3e2dad410214098913c3ae3f0b503e3666726#diff-cb73cbccfb145f8a678bc1d0dc9b56fcR38) ?

**Comment by tranchitellawfp** [comment]
> > I suggest closing this PR. While I support the addition of health checks, I believe this should be implemented in a common way exposing a `/healthz` end-point.
> 
> so you do not like that [/health](https://github.com/mendersoftware/deployments/pull/377/commits/acc3e2dad410214098913c3ae3f0b503e3666726#diff-cb73cbccfb145f8a678bc1d0dc9b56fcR38) ?

I don't like `/api/internal/v1/deployments`, but my comment was more about: we either do it in all the services in a "common way" or we don't do it in a single service.

**Comment by merlin-northern** [comment]
> > > I suggest closing this PR. While I support the addition of health checks, I believe this should be implemented in a common way exposing a `/healthz` end-point.
> > 
> > 
> > so you do not like that [/health](https://github.com/mendersoftware/deployments/pull/377/commits/acc3e2dad410214098913c3ae3f0b503e3666726#diff-cb73cbccfb145f8a678bc1d0dc9b56fcR38) ?
> 
> I don't like `/api/internal/v1/deployments/health`, but my comment was more about: we either do it in all the services in a "common way" or we don't do it in a single service.

originally I planned to move it into lib-go-micro. and make the /health endpoint common to all services, but did not find a good way, perhaps I will look again. putting all that on a side, the implementation of health can be different, as in this example, what do you think about that particular one?

**Comment by tranchitella** [comment]
I'm closing this PR, we already implemented health checks.

**Pull request closed without merging**
