### PR TITLE
MC-7155: Update accesslog and other dependencies

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Review by kjaskiewiczz — APPROVED** [review]
looks good; thanks for taking care of aws-sdk-go-v2 update!

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Pull request merged**
