### PR TITLE
docs: GET artifacts/{id}/devices

### PR DESCRIPTION
**Pull request by mchalski**
Issues: MEN-814

Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>

@mendersoftware/rndity @maciejmrowiec

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
We should not merge this until we end discussion about deployment creation/assignment mechanism.

**Comment by maciejmrowiec** [comment]
@kjaskiewiczz @mchalski ping ;) what shall we do with this one ?

**Comment by GregorioDiStefano** [comment]
ping

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano I think this was spec waiting to get implemented but the piece got postponed in backlog

**Comment by tranchitella** [comment]
Closing this old, outdated PR.

**Pull request closed without merging**
