### PR TITLE
fix: always reassign artifact on the device type change

### PR DESCRIPTION
**Pull request by kjaskiewiczz**

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Comment by tranchitella** [comment]
Failure in `test_deployment_two_devices_parallel_updates_one_failure` is not relevant. @kjaskiewiczz do you want me to merge?

**Comment by kjaskiewiczz** [comment]
@tranchitella yes please

**Comment by tranchitella** [comment]
@kjaskiewiczz merged!

**Comment by kjaskiewiczz** [comment]
@tranchitella thank you!

**Pull request merged**
