### PR TITLE
refac: Simplify s3.{FileStorage -> ObjectStorage} interface

### PR DESCRIPTION
**Pull request by alfrunes**
This refactoring removes some permission requirements in addition to simplifying the complexity of adding new ObjectStorage implementations.

### CODE REVIEW

**Comment by tranchitella** [comment]
@alfrunes shall we take the opportunity to move the code from `s3` to `objectstorage` and `objectstorage/s3`?

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --fast

**Review by tranchitella — APPROVED** [review]
Looks good. However, I thought you were going to implement unit tests using a real S3 service. Did you abort the idea?

**Comment by alfrunes** [comment]
> Looks good. However, I thought you were going to implement unit tests using a real S3 service. Did you abort the idea?

I will follow up on this with a separate ticket. The existing ones have already blown out of scope.

**Pull request merged**
