### PR TITLE
acceptance tests

### PR DESCRIPTION
**Pull request by bboozzoo**
It's a WIP, don't merge yet.

@maciejmrowiec @mendersoftware/rndity

### CODE REVIEW

**Comment by bboozzoo** [comment]
ready for review & merging

**Comment by bboozzoo** [comment]
FWIW integration jobs are failing due to unrelated reasons, acceptance tests are green

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano can you have a peek ?

**Comment by GregorioDiStefano** [comment]
@bboozzoo can you add a test to verify that a deployment status correctly reports the valid state at this end point: https://docs.mender.io/1.0/APIs/Management-APIs/Deployments#get-the-details-of-a-selected-deployment

**Comment by bboozzoo** [comment]
@GregorioDiStefano it's already checkd in a couple of places:
https://github.com/mendersoftware/deployments/pull/220/commits/adc53c1921c6df65d871ce35344a63359ee159f4#diff-21b1d858f64fe9145c83a0c63b6295e0R113
https://github.com/mendersoftware/deployments/pull/220/commits/adc53c1921c6df65d871ce35344a63359ee159f4#diff-21b1d858f64fe9145c83a0c63b6295e0R113
https://github.com/mendersoftware/deployments/pull/220/commits/adc53c1921c6df65d871ce35344a63359ee159f4#diff-21b1d858f64fe9145c83a0c63b6295e0R174
https://github.com/mendersoftware/deployments/pull/220/commits/adc53c1921c6df65d871ce35344a63359ee159f4#diff-21b1d858f64fe9145c83a0c63b6295e0R310
https://github.com/mendersoftware/deployments/pull/220/commits/adc53c1921c6df65d871ce35344a63359ee159f4#diff-21b1d858f64fe9145c83a0c63b6295e0R320

**Comment by GregorioDiStefano** [comment]
damn github UI doesn't load the entire changes unless you do some clicking...

**Comment by bboozzoo** [comment]
BTW. a number of observations (as it's the 3rd service to get acceptance tests):

* bravado is a so-so library, lacks DELETE support, method names are awkwardly long
** there's bravado-core (?!), but I can't tell what is the relation between the two
* it would be nice if our services provided api spec at one of the endpoints (yes, just like we did with WSDL in the past), this way we could avoid copying the spec files around, at least we'd be sure that the spec you get is the one that was used during the build

**Comment by GregorioDiStefano** [comment]
are you sure about the lacking delete support? I'm pretty sure it supports DELETE

**Comment by bboozzoo** [comment]
Last time I used delete was when writing deviceauth acceptance tests and you could call a method but there was no associated HTTP request going out (and no exception either).

**Comment by bboozzoo** [comment]
Any more changes needed here?

**Comment by bboozzoo** [comment]
@GregorioDiStefano replaced artifact deletion with this:
```
diff --git a/tests/tests/client.py b/tests/tests/client.py
index a857189..50f0319 100644
--- a/tests/tests/client.py
+++ b/tests/tests/client.py
@@ -121,11 +121,8 @@ class ArtifactsClient(SwaggerApiClient):
     def delete_artifact(self, artid=''):
         # delete it now (NOTE: not using bravado as bravado does not support
         # DELETE)
-        rsp = requests.delete(self.make_api_url('/artifacts/{}'.format(artid)), verify=False)
-        try:
-            assert rsp.status_code == 204
-        except AssertionError:
-            raise ArtifactsClientError('delete failed', rsp)
+
+        self.client.artifacts.delete_artifacts_id(Authorization='foo', id=artid)
```

and artifacts are no longer removed, there's no delete request to the backend at all ;)

**Comment by bboozzoo** [comment]
merge?

**Pull request merged**
