### PR TITLE
management_api.yml: fix broken link to docs.mender.io

### PR DESCRIPTION
**Pull request by mirzak**
Changelog: None

Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

### CODE REVIEW

**Comment by mirzak** [comment]
@tranchitella  Are the CI errors something caused by this change-set?

**Comment by tranchitella** [comment]
@mirzak nope, restarting the failed jobs

**Comment by tranchitella** [comment]
@mirzak the pipeline started with an old configuration, I'm starting a new one:
https://gitlab.com/Northern.tech/Mender/deployments/-/pipelines/176553851

**Comment by tranchitella** [comment]
@mirzak green now, merging.

**Pull request merged**
