### PR TITLE
Use MongoDB version to 3.6 in unit tests

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by tranchitella** [comment]
@lluiscampos unit tests pass now, but coverage publishing fails. What shall I do, now?

**Comment by kacf** [comment]
That one is new to me. @lluiscampos: Does the coveralls failure ring a bell?

**Comment by lluiscampos** [comment]
@tranchitella @kacf This PR https://github.com/mendersoftware/mendertesting/pull/118 should fix this problem, and potentially all other repos in Mender 2.4.x release branches.

**Comment by tranchitella** [comment]
@lluiscampos I'm testing it here: https://github.com/mendersoftware/deployments/pull/506/commits/6779480ca88a2bfc60e44fa2062153a06d8d864d

**Comment by tranchitella** [comment]
@lluiscampos @kacf ready for review

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
