### PR TITLE
added pip caching to travis file

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@bboozzoo

**Comment by bboozzoo** [comment]
merge?

**Comment by GregorioDiStefano** [comment]
it won't hurt, but it doesn't look like caching is working

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano https://travis-ci.org/mendersoftware/deployments/caches

**Comment by GregorioDiStefano** [comment]
yes, we are aware, but no idea why it's not working

**Pull request merged**
