### PR TITLE
Bumped gocyclo's complexity roof from 15 to 20

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: Title

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
For some background, we already did this in mender-artifact and have found it to be more "fair" at 20 than at 15. But would like input from the backend folks.

**Comment by oleorhagen** [comment]
From @lluiscampos in https://github.com/mendersoftware/deployments-enterprise/pull/19
> Few comments:
> 
>     * It think it is preferred to merge from os to enterprise. Cherry-picking will lead to conflicts sooner or later.
> 
>     * This change does not affect integ tests, so please stop the big pipeline
> 
>     * Why are we relaxing the criteria of gocyclo? This affects overall QA and I think more people needs to be involved (namely: me)

**Comment by oleorhagen** [comment]
Gocyclo is relaxed as gocyclo's limit of fifteeen seems to be too low for some regular code patterns

**Comment by oleorhagen** [comment]
@kacf @kjaskiewiczz 
See above

**Comment by lluiscampos** [comment]
> Gocyclo is relaxed as gocyclo's limit of fifteeen seems to be too low for some regular code patterns

Ok. Thanks for bringing me here to this PR

**Pull request merged**
